### PR TITLE
Fix css load when using manifest_name

### LINKED ISSUE #46: Failed to get CSS for route
Hi, I got the following error when I run `CriticalPathCss.generate_all` or `rake critical_path_css:generate`.

Error: Penthouse timed out after 60s. 
Failed to get CSS for route /
  with options={"url"=>"http://local.ayendarooms:3000/", "css"=>"/home/esteban/Desktop/ayenda/public/assets/distributions/application.css", "width"=>1300, "height"=>900, "timeout"=>60000, "forceInclude"=>[], "strict"=>false, "maxEmbeddedBase64Length"=>1000, "userAgent"=>"Penthouse Critical Path CSS Generator", "renderWaitTime"=>100, "blockJSRequests"=>true, "customPageHeaders"=>{"Accept-Encoding"=>"identity"}}

I checked and the file exists. Any help will be very useful, thanks

### PR DESCRIPTION
**Pull request by gr8bit**
Fixes #46, #50

### CODE REVIEW

**Comment by gr8bit** [comment]
@michael-misshore could you merge and release this please? <3

**Comment by michael-misshore** [comment]
@gr8bit My sincere apologies. Working on getting this published now.

**Comment by Tlazypanda** [comment]
@michael-misshore is this published yet? :sweat_smile:

**Comment by michael-misshore** [comment]
Yes.

https://rubygems.org/gems/critical-path-css-rails

**Comment by Tlazypanda** [comment]
Ohh thanks a lot! :smile:  @michael-misshore. The readme needs to be updated with this new version instead of 3.1.0. I would be happy to take this up :sweat_smile:

**Comment by michael-misshore** [comment]
Ruh roh lol. Up to you, else i'll get to it once I update some of the dependencies.

**Pull request merged**
